# Generated by Django 3.0.2 on 2020-01-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200106_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='nos',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='userid',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
